### ISSUE TITLE
Error: spwn ENAMETOOLONG

### ISSUE THREAD

**Issue by phroureo** [gitname/react-gh-pages#211]
# Category

Which of these applies to you? _(Select all that apply)_

- [x] I'm following the tutorial as-written from start to finish
- [ ] I'm using a custom domain (note: not covered in tutorial)
- [ ] I'm using React Router (note: not covered in tutorial)

# Step

Which step of the tutorial do you want someone to help you with? _(Select one)_

- [7] Step number: _(put the number here)_
- [ ] Something else

# Links

Tell us where we can find your code and your GitHub Pages site:

- GitHub repository (source code): https://github.com/phroureo/pf2e-tools
- GitHub Pages site (deployed app): https://phroureo.github.io/pf2e-tools/

# Everything else

I'm getting this error when I try to run `npm run deploy`: 

```
Error: spawn ENAMETOOLONG
    at ChildProcess.spawn (node:internal/child_process:420:11)
    at Object.spawn (node:child_process:757:9)
    at C:\Users\(folder)\source\repos\pf2e-tools\node_modules\gh-pages\lib\git.js:30:22
    at new Promise (<anonymous>)
    at spawn (C:\Users\(folder)\source\repos\pf2e-tools\node_modules\gh-pages\lib\git.js:29:10)
    at Git.exec (C:\Users\(folder)\source\repos\pf2e-tools\node_modules\gh-pages\lib\git.js:69:10)
    at Git.rm (C:\Users\(folder)\source\repos\pf2e-tools\node_modules\gh-pages\lib\git.js:146:15)
    at C:\Users\(folder)\source\repos\pf2e-tools\node_modules\gh-pages\lib\index.js:180:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I tried shortening long files and long file names, but am still having issues with this step.

**Comment by gitname** [comment]
Hi @phroureo, sorry about the delay in my response. I have not encountered this issue before. Are you still facing this issue?

If so, will you tell me how many characters are in the part of the path that you represented with `(folder)`? I don't need to know the actual string (in case it is private; e.g. it includes your real name).

Also, I see a 10 year-old issue in the `npm` repository involving that `ENAMETOOLONG` error code: https://github.com/npm/npm/issues/6776#issuecomment-65921433. I think the person that created that Issue had a file on their computer that had a very long name and was created by mistake. Will you check for any particularly long-named files or folders in your working directory?

**Comment by ThantHtetAung101** [comment]
This also happened with my project. I even made a python script to check the whole project if I got any files or folder which names are too long but I don't have any. Any clues?

**Comment by ismail-is** [comment]
what is error?

**Comment by ThantHtetAung101** [comment]
I've solved this by doing the workaround method. I still can't directly deploy. I first build my project using `npm run build` and I copied the whole dist or build folder into a seperate folder and link a fresh new github repo to it. I manually deploy the page by going to Project Repo -> Setting -> Pages. You can select a branch to deploy and wait a few minutes. The site will be up and running. If you made changes to your code, you will have to build or complie it again, copied the main js and css codes to build folder. Push the changes of the build folder to reflect changes.

**Comment by popol09** [comment]
facing same issue, ive been working with this problem for 3 days dang

**Comment by GoncaloFerreira-PT** [comment]
This also happened to me on windows and after running a script to check for long files it found that the problem was in node_modules\.cache\gh-pages

**Comment by VeronicaSj** [comment]
The proble has gotten solved by deleting the node_modules.cache\gh-pages and changing the folder name and changing the remote repository name.

**Comment by J-kailun** [comment]
Deleting node_modules/.cache/gp-pages did not resolve the issue.

**Comment by tapurika** [comment]
I had this problem too.
And I deleted node_modules/.cache/gp-pages,
But it didn't work for me.

Error: spawn ENAMETOOLONG
    at ChildProcess.spawn (node:internal/child_process:420:11)
    at Object.spawn (node:child_process:786:9)
    at D:\Github - project\tapurika\pir_bate_mesal\node_modules\gh-pages\lib\git.js:30:22
    at new Promise (<anonymous>)
    at spawn (D:\Github - project\tapurika\pir_bate_mesal\node_modules\gh-pages\lib\git.js:29:10)
    at Git.exec (D:\Github - project\tapurika\pir_bate_mesal\node_modules\gh-pages\lib\git.js:69:10)
    at Git.rm (D:\Github - project\tapurika\pir_bate_mesal\node_modules\gh-pages\lib\git.js:146:15)
    at D:\Github - project\tapurika\pir_bate_mesal\node_modules\gh-pages\lib\index.js:188:22
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
